In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [46]:
y2015 = pd.read_csv(
    'https://www.dropbox.com/s/0so14yudedjmm5m/LoanStats3d.csv?dl=1',
    skipinitialspace=True,
    header=1
)

In [47]:
y2015.describe()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
count,4.210950e+05,421095.000000,421095.000000,421095.000000,421095.000000,4.210950e+05,421095.000000,421095.000000,421095.000000,217133.000000,...,421095.000000,421095.000000,421095.000000,416856.000000,421095.000000,421095.000000,4.210950e+05,4.210950e+05,421095.000000,4.210950e+05
mean,5.759576e+07,15240.285862,15240.285862,15234.156412,441.860087,7.696561e+04,19.195989,0.347397,0.572690,34.023391,...,0.094318,2.170947,93.924313,47.527110,0.133188,0.064556,1.734070e+05,5.222199e+04,21958.208958,4.347865e+04
std,1.013358e+07,8571.325901,8571.325901,8567.935752,244.851179,7.394996e+04,23.504038,0.927695,0.867776,21.990270,...,0.522758,1.853858,8.875399,36.054458,0.385975,0.444231,1.756722e+05,4.907494e+04,21840.371112,4.394271e+04
min,7.082500e+04,1000.000000,1000.000000,900.000000,23.400000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.500000e+03,0.000000e+00,0.000000,0.000000e+00
25%,4.922617e+07,8500.000000,8500.000000,8500.000000,263.930000,4.600000e+04,12.590000,0.000000,0.000000,15.000000,...,0.000000,1.000000,90.900000,15.400000,0.000000,0.000000,5.090900e+04,2.259850e+04,7800.000000,1.548150e+04
50%,5.895358e+07,14000.000000,14000.000000,14000.000000,385.410000,6.500000e+04,18.600000,0.000000,0.000000,31.000000,...,0.000000,2.000000,97.400000,50.000000,0.000000,0.000000,1.114050e+05,3.959600e+04,15200.000000,3.297000e+04
75%,6.604584e+07,20000.000000,20000.000000,20000.000000,578.790000,9.169050e+04,25.340000,0.000000,1.000000,50.000000,...,0.000000,3.000000,100.000000,75.000000,0.000000,0.000000,2.496290e+05,6.565100e+04,28600.000000,5.829900e+04
max,7.354484e+07,35000.000000,35000.000000,35000.000000,1445.460000,9.500000e+06,9999.000000,39.000000,6.000000,176.000000,...,39.000000,30.000000,100.000000,100.000000,11.000000,85.000000,9.999999e+06,2.921551e+06,834300.000000,2.101913e+06

This is a big data frame with 85 columns and over 400,000 rows

In [48]:
y2015.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
421092,36271333,38982739.0,13000.0,13000.0,13000.0,60 months,15.99%,316.07,D,D2,...,0.0,3.0,100.0,50.0,1.0,0.0,51239.0,34178.0,10600.0,33239.0
421093,36490806,39222577.0,12000.0,12000.0,12000.0,60 months,19.99%,317.86,E,E3,...,1.0,2.0,95.0,66.7,0.0,0.0,96919.0,58418.0,9700.0,69919.0
421094,36271262,38982659.0,20000.0,20000.0,20000.0,36 months,11.99%,664.20,B,B5,...,0.0,1.0,100.0,50.0,0.0,1.0,43740.0,33307.0,41700.0,0.0
421095,Total amount funded in policy code 1: 6417608175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421096,Total amount funded in policy code 2: 1944088810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Last 2 rows need to be removed from the data frame

In [49]:
y2015 = y2015[:-2]

Checking the distinct counts of the categorical variables

In [50]:
categorical = y2015.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

id
421095
term
2
int_rate
110
grade
7
sub_grade
35
emp_title
120812
emp_length
11
home_ownership
4
verification_status
3
issue_d
12
loan_status
7
pymnt_plan
1
url
421095
desc
34
purpose
14
title
27
zip_code
914
addr_state
49
earliest_cr_line
668
revol_util
1211
initial_list_status
2
last_pymnt_d
25
next_pymnt_d
4
last_credit_pull_d
26
application_type
2
verification_status_joint
3

Dropping all the columns with more than 10 distinct counts. plus changing "int_rate" feature to numeric since it can not be categorical

In [51]:
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

# Drop other columns with many unique variables
y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util', 'sub_grade', 'addr_state', 'desc', 
            'emp_length', 'issue_d', 'purpose', 'title', 'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d'], 
           1, inplace=True)

Dropping all non important features and related ones

In [52]:
y2015.drop(['id', 'member_id', 'funded_amnt_inv',
       'mths_since_last_delinq',
       'mths_since_last_record', 
       'out_prncp_inv',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee',
       'dti_joint', 'verification_status_joint',
       'open_acc_6m',
       'open_il_6m', 'open_il_12m', 'open_il_24m',
       'il_util', 'open_rv_12m', 'open_rv_24m',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'inq_last_12m',
       'acc_open_past_24mths', 'bc_open_to_buy', 'bc_util',
       'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mths_since_recent_bc_dlq',
       'mths_since_recent_inq', 'mths_since_recent_revol_delinq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75'], 
           1, inplace=True)

get dummy columns for all remaining categorical features

In [53]:
pd.get_dummies(y2015)

,loan_amnt,funded_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,...,loan_status_Default,loan_status_Fully Paid,loan_status_In Grace Period,loan_status_Late (16-30 days),loan_status_Late (31-120 days),pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_INDIVIDUAL,application_type_JOINT
0,16000.0,16000.0,14.85,379.39,48000.0,33.18,0.0,0.0,11.0,2.0,...,0,0,0,0,0,1,0,1,1,0
1,9600.0,9600.0,7.49,298.58,60000.0,22.44,0.0,0.0,7.0,0.0,...,0,0,0,0,0,1,0,1,1,0
2,25000.0,25000.0,7.49,777.55,109000.0,26.02,0.0,1.0,9.0,0.0,...,0,1,0,0,0,1,0,1,1,0
3,28000.0,28000.0,6.49,858.05,92000.0,21.60,0.0,0.0,16.0,0.0,...,0,0,0,0,0,1,0,1,1,0
4,8650.0,8650.0,19.89,320.99,55000.0,25.49,0.0,4.0,18.0,1.0,...,0,1,0,0,0,1,0,1,1,0
5,23000.0,23000.0,8.49,471.77,64000.0,18.28,0.0,0.0,21.0,0.0,...,0,0,0,0,0,1,0,1,1,0
6,29900.0,29900.0,12.88,678.49,65000.0,21.77,0.0,0.0,15.0,0.0,...,0,0,0,0,0,1,0,1,1,0
7,18000.0,18000.0,11.99,400.31,112000.0,8.68,0.0,0.0,17.0,0.0,...,0,1,0,0,0,1,0,1,1,0
8,35000.0,35000.0,14.85,829.90,110000.0,17.06,0.0,0.0,13.0,0.0,...,0,0,0,0,0,1,0,1,1,0
9,10400.0,10400.0,22.45,289.91,104433.0,25.37,1.0,3.0,12.0,0.0,...,0,1,0,0,0,1,0,1,1,0
10,20000.0,20000.0,10.78,432.66,63000.0,10.78,0.0,0.0,6.0,0.0,...,0,0,0,0,0,1,0,1,0,1
11,22400.0,22400.0,12.88,508.30,95000.0,22.98,0.0,0.0,16.0,0.0,...,0,0,0,0,0,1,0,1,1,0
12,16000.0,16000.0,12.88,363.07,70000.0,26.40,0.0,0.0,13.0,0.0,...,0,0,0,0,0,1,0,1,1,0
13,3600.0,3600.0,13.99,123.03,55000.0,5.91,0.0,1.0,7.0,0.0,...,0,0,0,0,0,1,0,1,1,0
14,24700.0,24700.0,11.99,820.28,65000.0,16.06,1.0,4.0,22.0,0.0,...,0,1,0,0,0,1,0,1,1,0
15,10000.0,10000.0,6.49,306.45,85000.0,13.07,0.0,1.0,14.0,1.0,...,0,0,0,0,0,1,0,1,1,0
16,1400.0,1400.0,12.88,47.10,64000.0,34.95,0.0,0.0,17.0,0.0,...,0,0,0,0,0,1,0,1,1,0
17,11950.0,11950.0,13.44,405.18,34000.0,10.20,0.0,0.0,5.0,0.0,...,0,0,0,0,0,1,0,1,1,0
18,18000.0,18000.0,19.48,471.70,150000.0,9.39,0.0,1.0,18.0,1.0,...,0,0,0,0,0,1,0,1,1,0
19,8000.0,8000.0,11.48,263.74,42000.0,34.80,0.0,0.0,8.0,0.0,...,0,0,0,0,0,1,0,1,1,0
20,20000.0,20000.0,8.49,631.26,85000.0,17.61,1.0,0.0,8.0,0.0,...,0,0,0,0,0,1,0,1,1,0
21,20000.0,20000.0,9.17,637.58,180000.0,14.67,0.0,0.0,12.0,0.0,...,0,1,0,0,0,1,1,0,1,0
22,28000.0,28000.0,13.44,949.38,125000.0,7.49,0.0,0.0,6.0,0.0,...,0,0,0,0,0,1,0,1,1,0
23,5000.0,5000.0,13.44,169.54,79000.0,12.70,0.0,0.0,3.0,0.0,...,0,0,0,0,0,1,0,1,1,0
24,20000.0,20000.0,5.32,602.30,65000.0,18.83,0.0,1.0,12.0,0.0,...,0,0,0,0,0,1,0,1,1,0
25,4225.0,4225.0,14.85,146.16,35000.0,15.22,2.0,0.0,6.0,0.0,...,0,0,0,0,0,1,0,1,1,0
26,15000.0,15000.0,5.32,451.73,44000.0,15.34,0.0,1.0,7.0,0.0,...,0,0,0,0,0,1,0,1,1,0
27,17600.0,17600.0,5.32,530.03,88000.0,26.59,0.0,0.0,20.0,0.0,...,0,1,0,0,0,1,0,1,1,0
28,6000.0,6000.0,7.49,186.61,100000.0,13.28,1.0,1.0,9.0,0.0,...,0,0,0,0,0,1,0,1,1,0
29,16000.0,16000.0,12.88,538.18,65000.0,18.96,0.0,0.0,7.0,1.0,...,0,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421065,13000.0,13000.0,8.19,408.52,85000.0,8.05,1.0,0.0,8.0,0.0,...,0,0,0,0,0,1,1,0,1,0
421066,15000.0,15000.0,11.99,498.15,70000.0,8.47,0.0,0.0,8.0,0.0,...,0,0,0,0,0,1,0,1,1,0
421067,20000.0,20000.0,6.99,617.46,72000.0,27.24,0.0,1.0,15.0,0.0,...,0,0,0,0,0,1,1,0,1,0
421068,4200.0,4200.0,15.99,147.64,48000.0,36.93,0.0,0.0,13.0,0.0,...,0,0,0,0,0,1,1,0,1,0
421069,26950.0,26950.0,8.19,846.88,54000.0,18.11,0.0,0.0,14.0,0.0,...,0,1,0,0,0,1,1,0,1,0
421070,23000.0,23000.0,15.59,554.32,50000.0,31.95,0.0,0.0,13.0,0.0,...,0,0,0,0,0,1,0,1,1,0
421071,18700.0,18700.0,17.86,473.44,52000.0,11.28,0.0,0.0,8.0,0.0,...,0,1,0,0,0,1,0,1,1,0
421072,6000.0,6000.0,17.86,216.50,90000.0,2.84,0.0,0.0,9.0,0.0,...,0,0,0,0,0,1,1,0,1,0
421073,15000.0,15000.0,11.44,329.44,57000.0,15.77,0.0,0.0,8.0,0.0,...,0,0,0,0,0,1,0,1,1,0
421074,25000.0,25000.0,15.99,607.82,103000.0,5.27,0.0,0.0,5.0,0.0,...,0,0,0,0,1,1,0,1,1,0
421075,26500.0,26500.0,8.67,545.87,92000.0,29.60,1.0,0.0,10.0,0.0,...,0,0,0,0,0,1,0,1,1,0
421076,25000.0,25000.0,15.59,602.52,55000.0,5.52,0.0,0.0,9.0,0.0,...,0,1,0,0,0,1,1,0,1,0
421077,21000.0,21000.0,6.03,639.15,65000.0,17.09,0.0,0.0,11.0,0.0,...,0,0,0,0,0,1,1,0,1,0
421078,8000.0,8000.0,8.19,251.40,50000.0,17.62,0.0,1.0,11.0,0.0,...,0,0,0,0,0,1,1,0,1,0
421079,12000.0,12000.0,9.49,384.34,40000.0,25.65,1.0,0.0,8.0,0.0,...,0,1,0,0,0,1,1,0,1,0
421080,10000.0,10000.0,6.49,306.45,75000.0,33.66,0.0,0.0,9.0,0.0,...,0,0,0,0,0,1,0,1,1,0
421081,13150.0,13150.0,14.99,312.77,30000.0,1.00,0.0,0.0,3.0,0.0,...,0,1,0,0,0,1,0,1,1,0
421082,6225.0,6225.0,16.49,220.37,27000.0,18.58,0.0,1.0,3.0,0.0,...,0,1,0,0,0,1,1,0,1,0
421083,10775.0,10775.0,6.03,327.95,54000.0,13.22,1.0,0.0,9.0,0.0,...,0,1,0,0,0,1,0,1,1,0
421084,7000.0,7000.0,14.31,240.30,57000.0,16.80,2.0,3.0,13.0,2.0,...,0,0,0,0,0,1,0,1,1,0
421085,4000.0,4000.0,8.67,126.59,50000.0,12.63,0.0,0.0,11.0,1.0,...,0,1,0,0,0,1,1,0,1,0
421086,7500.0,7500.0,9.49,240.22,40000.0,25.63,0.0,0.0,10.0,1.0,...,0,0,0,0,0,1,1,0,1,0
421087,10850.0,10850.0,19.24,399.04,32000.0,29.44,0.0,1.0,9.0,0.0,...,0,0,0,0,0,1,1,0,1,0
421088,11575.0,11575.0,15.59,404.61,25400.0,27.08,0.0,0.0,9.0,0.0,...,0,1,0,0,0,1,1,0,1,0
421089,12000.0,12000.0,11.99,398.52,63000.0,23.69,1.0,0.0,13.0,0.0,...,0,0,0,0,0,1,1,0,1,0
421090,10000.0,10000.0,11.99,332.10,31000.0,28.69,0.0,0.0,9.0,1.0,...,0,0,0,0,0,1,1,0,1,0
421091,24000.0,24000.0,11.99,797.03,79000.0,3.90,0.0,1.0,5.0,0.0,...,0,0,0,0,0,1,1,0,1,0
421092,13000.0,13000.0,15.99,316.07,35000.0,30.90,0.0,0.0,9.0,1.0,...,0,0,0,0,0,1,0,1,1,0
421093,12000.0,12000.0,19.99,317.86,64400.0,27.19,1.0,2.0,17.0,0.0,...,0,0,0,0,0,1,0,1,1,0
421094,20000.0,20000.0,11.99,664.20,100000.0,10.83,0.0,1.0,8.0,1.0,...,0,0,0,0,0,1,1,0,1,0

In [55]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

print(cross_val_score(rfc, X, Y, cv=10))
print(cross_val_score(rfc, X, Y, cv=10).mean())

C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

[0.95685213 0.96022417 0.96058037 0.96031916 0.95984327 0.95939207
 0.95991356 0.96019853 0.95908044 0.95919821]

C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

0.9596718064931512

The model performed well after dropping almost 50% of the features included in the original model. average R-Square for this model is more than 0.9 and very close to the original model average R-Square of 0.97

Now lets drop the features related to payment amount and outstanding principal and check the accuracy of the model

In [56]:
y2015.drop(['out_prncp', 'total_pymnt','last_pymnt_amnt'], 1, inplace=True)

In [33]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

print(cross_val_score(rfc, X, Y, cv=10))
print(cross_val_score(rfc, X, Y, cv=10).mean())

C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

[0.68407305 0.68210206 0.68656646 0.68773005 0.69095227 0.68917122
 0.68873637 0.68923508 0.6896003  0.6716145 ]

C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

0.6849522230368739

The R-Square went down too much after removing these 3 features. This shows the importants of these features for the model